### ISSUE TITLE
Online version

### ISSUE THREAD

**Issue by crazko** [ChristianTietze/NowPageAggregatorPHP#1]
I've put your code on Heroku, so it can be seen/tested without running it locally.

https://hnow.herokuapp.com/

Thanks for the h-now proposal, I'll add it to my now page, though it can be parsed correctly even without it :)

Maybe you'd interested to have it deployed yourself from your repository and not from [my fork](https://github.com/crazko/NowPageAggregatorPHP). In that case I'll yield you the app name in Heroku.

**Comment by DivineDominion** [comment]
@crazko That's cool! Thanks! I've postponed this kind of thing because I have no clue about anything cloud-related. That's a very welcome contribution :)

I wouldn't know how to maintain this; if you don't mind, we can keep it up with your fork at the moment. I invited you as a contributor so you don't have to maintain the fork on your own, but no pressure to accepting this!

**Comment by crazko** [comment]
Sure, lets see if it will work from this repository and my account.

So, is it OK if I create a PR to add here files needed for the run on Heroku? It means it will be updated on every commit to the `master` branch.

**Comment by DivineDominion** [comment]
Sure, go ahead! I'll eventually protect `master` from committing to it directly if we continue to collaborate on the code, but for now, your free to do what's necessary to `master` directly -- or open a PR if you're more comfortable with that.

**Comment by crazko** [comment]
OK, great! You should receive an email - I've requested access to this repository for Heroku app, after that I should be able to connect it together.

**Comment by DivineDominion** [comment]
Access granted 👍

**Comment by crazko** [comment]
Well, I'm afraid I'm stuck. I thought that it will work with my and Heroku access to the repository, but it isn't. From [their documentation](https://devcenter.heroku.com/articles/github-integration#why-can-t-heroku-access-my-github-repository):

> [Heroku can't access repository when] The GitHub user is an outside collaborator on an organisation, which isn’t currently supported. The user needs to be a member of the organisation.

Only now I can see that your account's type is not personal, but an organisation. Which gives us, at least, three options:

1. I can share a simple step-by-step tutorial how to set up Heroku
1. make me member of an organisation, which would be probably overkill
1. I set mirroring GitHub action to my own repository

Question aside: is it intentional to have your account organisation?

**Comment by DivineDominion** [comment]
Oh no :/ 

I organize my repos into GH orgs to keep things apart from each other. I try not to put a lot of long-lived stuff in my personal account. Meh.

I don't mind adding you to the org, though it's probably awkward for you, too :)

A step-by-step guide might come in handy if folks want to play with this (or aggregator like this) and then have it online somewhere. If you absolutely don't mind, a PR with Heroku setup instructions in a separate Markdown file or as part of the README, depending on how long the instructions get.

Sorry for the anticlimax :)
